### ISSUE TITLE
published QOS 2 messages remain in flight

### ISSUE THREAD

**Issue by emilesalem** [goiiot/libmqtt#39] opened 2020-11-17 14:47 UTC
how to verify:
- set mqtt config option max_inflight_messages to 1
- subscribe to topic A with QOS 2
- publish to topic A with QOS 2
- receive first message on topic A
- wait x seconds to clear any chance of message remaining in flight
- publish to topic A with QOS 2
- never receive second message on topic A

**Comment by emilesalem** [comment] 2020-11-17 16:39
this program shows the issue
`package main

import (
	"fmt"
	"log"
	"time"

	"github.com/goiiot/libmqtt"
)

func main() {

	c, err := libmqtt.NewClient(
		libmqtt.WithVersion(libmqtt.V311, true),
		libmqtt.WithAutoReconnect(true),
		libmqtt.WithIdentity("guest", "guest"),
		libmqtt.WithClientID("pinger"),
	)
	if err != nil {
		log.Fatal(err)
	}
	if err := c.ConnectServer("127.0.0.1:1883"); err != nil {
		log.Fatal(err)
	}
	c.HandleTopic("hello", func(c libmqtt.Client, handledTopic string, qos libmqtt.QosLevel, message []byte) {
		log.Println("received message: ", string(message))
	})
	go c.Subscribe(&libmqtt.Topic{
		Name: "hello",
		Qos:  libmqtt.Qos2,
	})
	var i int
	t := time.NewTicker(3 * time.Second)
	for range t.C {
		c.Publish(&libmqtt.PublishPacket{
			Qos:       libmqtt.Qos2,
			TopicName: "hello",
			Payload:   []byte(fmt.Sprintf("#%v", i)),
		})
		i++
		if i == 3 {
			break
		}
	}
	select {}
}
`

**Comment by jeffreystoke** [comment] 2020-11-29 10:46
Hi @emilesalem , thanks for your feedback.

May I ask for more details regarding your mqtt broker setup and version of `libmqtt` you are using? If you are using the latest version, can you reproduce this issue with previous versions?

**Comment by jeffreystoke** [comment] 2020-12-02 00:40
I have reproduced this against emqx using qos1 or qos2, but may be different from your case, here is my environment and result (both producer and consumer using libmqtt):

- Setup emqx in remote vps (high latency, low throughput), deploy test producer there
- (test consumer) Subscribe topic FOO qos1 from remote emqx
- (test producer) Publish a lot of packets to topic FOO qos1

according to emqx dashboard:
- No data inflight in producer side
- data inflight in consumer side and resulted network error (disconnected by emqx, `enotconn`)
- If consumer side reconnected to broker, it will be able to consume inflight packets slowly (requires multiple reconnect)
- finally there will be no inflight packets in consumer side

So it tells Publish is working, and the problem probably lies in message receiving or emqx inflight handling, I am looking into this now.

**Comment by jeffreystoke** [comment] 2020-12-02 00:51
@emilesalem can you check if your mqtt connection is alive after first package received? more specifically, create client using `WithNetHandleFunc`, `WithConnHandleFunc` and `WithLog` for detailed debug information

**Comment by jeffreystoke** [comment] 2020-12-02 01:17
similar issues with `CleanSession=false` (which is your case) in emqx, can confirm it requires more investigation:

- https://github.com/emqx/emqx/issues/2512
- https://github.com/emqx/emqx/issues/3779

**Comment by emilesalem** [comment] 2020-12-06 04:20
> May I ask for more details regarding your mqtt broker setup and version of libmqtt you are using? 
using eclipse-mosquitto:1.6.12 and libmqtt 0.9.6

> If you are using the latest version, can you reproduce this issue with previous versions? 
reproduced with 0.9.5

**Comment by emilesalem** [comment] 2020-12-06 04:21
> can you check if your mqtt connection is alive after first package received?

connection is kept alive throughout publishes

**Comment by emilesalem** [comment] 2020-12-06 04:29
issue must be with libmqtt as same exact test done with paho (github.com/eclipse/paho.golang v0.9.1-0.20201006131139-9638458a263e) goes through without dangling messages left in flight.

**Comment by jeffreystoke** [comment] 2020-12-06 04:52
> issue must be with libmqtt as same exact test done with paho (github.com/eclipse/paho.golang v0.9.1-0.20201006131139-9638458a263e) goes through without dangling messages left in flight.

thanks, but I couldn't understand the meaning of that, can you explain a bit more?

btw, can you test the client connecting with `CleanSession=true`, just in case your issue with mosquitto is the same with emqx

**Comment by emilesalem** [comment] 2020-12-06 12:03
the issue is not on publishing but on receiving message.
libmqtt is not respecting QOS2 protocol, broker logs show:
mosquitto_1     | 1607255628: Sending PUBLISH to pinger (d0, q2, r0, m1, 'hello', ... (2 bytes))
mosquitto_1     | 1607255628: Received PUBREL from pinger (Mid: 2)

message receiver should reply with PUBREC, not PUBREL.

**Comment by emilesalem** [comment] 2020-12-06 12:51
> btw, can you test the client connecting with CleanSession=true, just in case your issue with mosquitto is the same with emqx

behaviour remains the same with CleanSession true

**Comment by emilesalem** [comment] 2020-12-06 13:19
I suspect this problem would only arise when subscribing and publishing to the same topic.It looks like libmqtt is using the same IDs in its sender and receiver flows.
Upon receiving PUBCOMP from the broker, libmqtt sender frees the packet ID (client_conn.go line 186).
Then, when limbqtt receiver gets PUBREL from the broker, it tries to retrieve the packet ID it previously freed (client_conn.go line 162), doesnt find it and the PUBCOMP is never sent, leaving messages in flight.

**Comment by jeffreystoke** [comment] 2020-12-06 13:56
Yes, you right, are you willing to fix this by opening a pull request so we can have you as a contributor since you have devoted so much effort troubleshooting.

Thank you a lot!

**Comment by emilesalem** [comment] 2020-12-06 15:13
To solve this I would try to replicate Paho's logic, but what purpose would this serve, in this case why not just use Paho ? :)

It seems like efforts would be better directed at supporting MQTT5 which Paho hasnt finished yet in golang (in beta).

Good luck in your efforts.

**Comment by jeffreystoke** [comment] 2020-12-06 15:19
Understood, thanks anyway!

Closing due to no more attention required.

**Closed by jeffreystoke** 2020-12-06 15:19 UTC
